### ISSUE TITLE
[Bug]: Not Working with HA 2026.8.3

### ISSUE THREAD

**Issue by guillochon** [firstof9/ha-openei#141]
### The problem

Refuses to start in this version

### What version of Home Assistant?

2026.8.3

### What version of ha-openei?

0.2.0

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.setup
Source: setup.py:341
First occurred: 11:00:02 AM (1 occurrence)
Last logged: 11:00:02 AM

Setup failed for custom integration 'openei': Unable to import component: cannot import name 'wrap' from 'aiofiles.base' (/usr/local/lib/python3.14/site-packages/aiofiles/base.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1091, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/openei/__init__.py", line 6, in <module>
    import openeihttp
  File "/usr/local/lib/python3.14/site-packages/openeihttp/__init__.py", line 3, in <module>
    from .client import Rates
  File "/usr/local/lib/python3.14/site-packages/openeihttp/client.py", line 14, in <module>
    from .cache import OpenEICache
  File "/usr/local/lib/python3.14/site-packages/openeihttp/cache.py", line 9, in <module>
    import aiofiles.os
  File "/usr/local/lib/python3.14/site-packages/aiofiles/os.py", line 5, in <module>
    from . import ospath as path
  File "/usr/local/lib/python3.14/site-packages/aiofiles/ospath.py", line 5, in <module>
    from .base import wrap
ImportError: cannot import name 'wrap' from 'aiofiles.base' (/usr/local/lib/python3.14/site-packages/aiofiles/base.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1051, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1091, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/openei/__init__.py", line 6, in <module>
    import openeihttp
  File "/usr/local/lib/python3.14/site-packages/openeihttp/__init__.py", line 3, in <module>
    from .client import Rates
  File "/usr/local/lib/python3.14/site-packages/openeihttp/client.py", line 14, in <module>
    from .cache import OpenEICache
  File "/usr/local/lib/python3.14/site-packages/openeihttp/cache.py", line 9, in <module>
    import aiofiles.os
  File "/usr/local/lib/python3.14/site-packages/aiofiles/os.py", line 5, in <module>
    from . import ospath as path
  File "/usr/local/lib/python3.14/site-packages/aiofiles/ospath.py", line 5, in <module>
    from .base import wrap
ImportError: cannot import name 'wrap' from 'aiofiles.base' (/usr/local/lib/python3.14/site-packages/aiofiles/base.py)
```

**Comment by firstof9** [comment]
Please include logs from home assistant for troubleshooting.

**Comment by guillochon** [comment]
@firstof9 added a log of I think the relevant error, preventing openei from loading.

**Comment by firstof9** [comment]
Have you restarted Home Assistant? This looks like an error when the library hasn't updated yet.

**Comment by guillochon** [comment]
I had restarted it already...but tried restarting it again now, and now it works? Sorry for the false alarm!
